name = "ScholarS2"
author = "StormcallerWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db132e9367ae0f1f4ea6e4f274d3a3bc066464b2f4eb773aaf031fe5e6ec2aac"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
