name = "ScholarS2"
author = "StormcallerWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40a5923ce7fc9679383557a22b3d45127796b1f4058c41c4ee22285b578bce98"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
