name = "ScholarS2"
author = "StormcallerWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e054c87cdb2a2240f4afd712dba595374b8cd580c992ba258232cdc4f1cb9763"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
