name = "ScholarS2"
author = "StormcallerWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cefcc0c0c28e18d739675c156cd004ff82c32a4e406828dee4ef658af185cc0"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
