name = "ScholarS2"
author = "StormcallerWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1487dcaaebac2f960c8df5d90f82a000ec3d59f53ddfbad1dac14f6d94a8cfa9"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
