name = "ScholarS2"
author = "StormcallerWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8de2ae2b634013216fa2f7c813bc6de3428ac1c4e5fb67b0249e30957957019"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
