name = "ScholarS2"
author = "StormcallerWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "116d22a6baf656f242a8569d1c0ae0e8a8bc3b6f00ec7bba1424292357f84a46"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
