name = "ScholarS2"
author = "StormcallerWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98ac05ac986b7986b130d2c619ce892ee5297234d811cd360bdd3f94b0e95f09"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
